# Generated by Django 5.1.7 on 2025-03-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiester_page',
            name='userid',
        ),
    ]
