# Generated by Django 5.1.7 on 2025-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_regiester_page_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
